name: jdk11 build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for Maven & JDK 11
      uses: xlui/action-maven-cli@v1.1
    - name: Build with Maven
      run: mvn -B package --file java/pom.xml -P jdk9
    - name: Test with Maven
      run: mvn test --file java/pom.xml -P jdk9
